/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.toedter.calendar;


import QLBH.CTHD;
import QLBH.ChiTiet;
import QLBH.Helpers.DataValidator;
import QLBH.Helpers.MessageDialogHelper;
import QLBH.HoaDon;
import QLBH.KhachHang;
import QLBH.NhanVien;
import QLBH.SanPham;
import QLBH.dao.CTHDDAO;
import QLBH.dao.ChiTietDao;
import QLBH.dao.HoaDonDao;
import QLBH.dao.KhachHangDao;
import QLBH.dao.NhanVienDao;
import QLBH.dao.SanPhamDao;
import QLBH.ui.MainForm;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author VAN ANH
 */
public class HDBHPanel extends javax.swing.JPanel {
  private JOptionPane parentForm;
   private final ArrayList<ChiTiet> list;
      private final ArrayList<HoaDon> listHD;
     int Sohd_present;

    private DefaultTableModel tblModel;
    protected static String SOHDTV;

    private final ArrayList<CTHD> listCT;
    
    /**
     * Creates new form HDBHPanel
     */
    public HDBHPanel(int sohd)  {
        Sohd_present=sohd;
        initComponents();
        showCombo();
        showCombo1();
        showCombo2();
        listHD = new HoaDonDao().getListHD();
        txtSOHD.setText(String.valueOf(sohd));
        SOHDTV=String.valueOf(sohd);
        list = new ChiTietDao().getListCT();
        initTable();
        loadData();
        //nút làm mới
        txtSL.setText("");
        txtGIA.setText("");
        txtNUOCSX.setText("");
        txtTENSP.setText("");
        txtTONGGIA.setText("");
        txtNGHD.setText("");
        txtHOTEN.setText("");
        txtTENNV.setText("");
        txtSODT.setText("");
        txtDCHI.setText("");
       
        
        
       this.listCT = null;
    }
    
     private void initTable() {
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Mã SẢN PHẨM", "TÊN SẢN PHẨM", "NƯỚC SẢN XUẤT", "GIÁ",
            "ĐƠN VỊ TÍNH", "SỐ LƯỢNG", "TỔNG GIÁ"});
        tblCHITIET.setModel(tblModel);
        showCombo();
    }
    private void showCombo2()  {
     SanPhamDao dao = new SanPhamDao();
        List<String> data = null;
        try {
            data = dao.getData();
        } catch (Exception ex) {
            Logger.getLogger(HDBHPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String string : data) {
           cbbMASP.addItem(string);
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbbMANV = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTENNV = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSOHD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNGHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtHOTEN = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDCHI = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSODT = new javax.swing.JTextField();
        cbbMAKH = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cbbMASP = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtTENSP = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtNUOCSX = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtGIA = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtTONGGIA = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSL = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCHITIET = new javax.swing.JTable();
        txtTONG = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();

        jLabel5.setText("Mã Nhân Viên");

        cbbMANV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbMANVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbbMANVMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbMANVMousePressed(evt);
            }
        });
        cbbMANV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMANVActionPerformed(evt);
            }
        });

        jLabel8.setText("Tên Nhân Viên");

        txtTENNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTENNVActionPerformed(evt);
            }
        });

        jLabel4.setText("Số Hóa Đơn");

        txtSOHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSOHDActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày Bán");

        jLabel3.setText("Mã Khách Hàng");

        jLabel7.setText("Họ Tên");

        jLabel9.setText("Địa Chỉ");

        jLabel10.setText("Số Điện Thoại");

        cbbMAKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbbMAKHMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cbbMAKHMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cbbMAKHMousePressed(evt);
            }
        });
        cbbMAKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMAKHActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNGHD)
                    .addComponent(txtTENNV)
                    .addComponent(cbbMANV, 0, 163, Short.MAX_VALUE)
                    .addComponent(txtSOHD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(37, 37, 37)
                        .addComponent(txtDCHI))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(37, 37, 37)
                        .addComponent(txtHOTEN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSODT))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbMAKH, 0, 162, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbbMAKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtHOTEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDCHI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSODT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSOHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNGHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cbbMANV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtTENNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );

        jLabel11.setText("Mã Sản Phẩm");

        cbbMASP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMASPActionPerformed(evt);
            }
        });

        jLabel12.setText("Tên Sản Phẩm");

        jLabel13.setText("Nước Sản Xuất");

        jLabel14.setText("Giá");

        jLabel15.setText("Thành Tiền");

        txtTONGGIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTONGGIAActionPerformed(evt);
            }
        });

        jLabel16.setText("Số Lượng");

        txtSL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLActionPerformed(evt);
            }
        });

        tblCHITIET.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCHITIET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCHITIETMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblCHITIET);

        txtTONG.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        txtTONG.setForeground(new java.awt.Color(0, 153, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 102));
        jLabel2.setText("Tổng:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTENSP)
                            .addComponent(cbbMASP, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNUOCSX)
                            .addComponent(txtGIA, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTONGGIA)
                            .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 648, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTONG, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel14))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cbbMASP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtTENSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(txtGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNUOCSX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(txtSL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel15)
                                .addComponent(txtTONGGIA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTONG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLoad.setText("Load");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnLoad)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLamMoi)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(btnCapNhat, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnLoad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnLamMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapNhat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbbMANVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMANVActionPerformed
        // TODO add your handling code here:       
        NhanVienDao dao = new NhanVienDao();
        NhanVien nv = new NhanVien();
         String selectedItem = (String)cbbMANV.getSelectedItem();
        System.out.println(selectedItem);
        try {
            nv = dao.FindByID(selectedItem);
            txtTENNV.setText(nv.getHOTEN());
        } catch (Exception ex) {
            Logger.getLogger(HDBHPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbbMANVActionPerformed

      private void loadData() {
        try {
            double tong=0.0;
            ChiTietDao dao = new ChiTietDao();
            List<ChiTiet> list = dao.FindAll();
            tblModel.setRowCount(0);
            txtSOHD.setText(SOHDTV);
            
            for (ChiTiet n : list) {
                
                if(n.getSOHD() == null ? SOHDTV == null : n.getSOHD().equals(SOHDTV)){
                    tong+=n.getTONGGIA();
                    tblModel.addRow(new Object[]{
                    n.getMASP(), n.getTENSP(), n.getNUOCSX(), n.getGIA(),
                    n.getDVT(), n.getSL(), n.getTONGGIA()});
                }
            }
            txtTONG.setText(String.valueOf(tong));
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.getMessage(), "Lỗi!");
        }

    }
    
    private void txtTENNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTENNVActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtTENNVActionPerformed

    private void cbbMANVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbMANVMousePressed
       
        
    }//GEN-LAST:event_cbbMANVMousePressed

    private void cbbMANVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbMANVMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMANVMouseEntered

    private void cbbMANVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbMANVMouseClicked

    }//GEN-LAST:event_cbbMANVMouseClicked

    private void txtSOHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSOHDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSOHDActionPerformed

    private void cbbMAKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbMAKHMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMAKHMouseClicked

    private void cbbMAKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbMAKHMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMAKHMouseEntered

    private void cbbMAKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbbMAKHMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbMAKHMousePressed

    private void cbbMAKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMAKHActionPerformed
        // TODO add your handling code here:
        KhachHangDao dao = new KhachHangDao();
        KhachHang kh = new KhachHang();
         String selectedItem = (String)cbbMAKH.getSelectedItem();
        System.out.println(selectedItem);
        try {
            if(selectedItem!="NULL"){
            kh = dao.FindByID(selectedItem);
            txtHOTEN.setText(kh.getHoTen());
            txtDCHI.setText(kh.getDChi());
            txtSODT.setText(kh.getSdt());
            } else{
            txtHOTEN.setText("");
            txtDCHI.setText("");
            txtSODT.setText("");
            }
        } catch (Exception ex) {
            Logger.getLogger(HDBHPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbbMAKHActionPerformed
String selectedItem1;
    private void cbbMASPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMASPActionPerformed
        // TODO add your handling code here:
        SanPhamDao dao = new SanPhamDao();
        SanPham sp = new SanPham();
        selectedItem1 = (String)cbbMASP.getSelectedItem();
        System.out.println(selectedItem1);
        try {

            sp = dao.FindByID(selectedItem1);
            txtTENSP.setText(sp.getTenSP());
            txtNUOCSX.setText(sp.getNuocSX());
            txtGIA.setText(String.valueOf(sp.getGia()));
            //txtDVT.setText(sp.getDVT());

        } catch (Exception ex) {
            Logger.getLogger(HDBHPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbbMASPActionPerformed

    private void txtTONGGIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTONGGIAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTONGGIAActionPerformed

    private void txtSLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLActionPerformed
        // TODO add your handling code here:
        if(!txtSL.getText().equals(null))
        txtTONGGIA.setText(String.valueOf(Double.parseDouble(txtGIA.getText())*Integer.parseInt(txtSL.getText())));
        else
        txtTONGGIA.setText("");

    }//GEN-LAST:event_txtSLActionPerformed

    private void tblCHITIETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCHITIETMouseClicked
        try {
            int row = tblCHITIET.getSelectedRow();
            if (row >= 0) {
                String id = (String) tblCHITIET.getValueAt(row, 0);
                ChiTietDao dao = new ChiTietDao();
                ChiTiet n = dao.FindByID1(SOHDTV,id);
                if (n != null) {
                    cbbMASP.setSelectedItem(n.getMASP());
                    txtTENSP.setText(n.getTENSP());
                    txtNUOCSX.setText(n.getNUOCSX());
                    txtGIA.setText(String.valueOf(n.getGIA()));

                  //  txtDVT.setText(n.getDVT());
                    txtSL.setText(String.valueOf(n.getSL()));
                    txtTONGGIA.setText(String.valueOf(n.getTONGGIA()));
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialogHelper.showErrorDialog(parentForm, e.toString(), "Lỗi");
        }
    }//GEN-LAST:event_tblCHITIETMouseClicked

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        // TODO add your handling code here:
          txtSL.setText("");
       // txtDVT.setText("");
        txtGIA.setText("");
        txtNUOCSX.setText("");
        txtTENSP.setText("");
        txtTONGGIA.setText("");
    
        loadData();
    }//GEN-LAST:event_btnLamMoiActionPerformed
  int flag=0;
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       
        //thêm hóa đơn
       
         StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtSOHD, sb, "Số hóa đơn không được để trống.");
        DataValidator.validateEmpty(txtNGHD, sb, "Ngày hóa đơn không được để trống.");
        DataValidator.validateEmpty(txtTONG, sb, "Trị giá không được để trống.");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }

        HoaDon n1 = new HoaDon();
        n1.setSoHD(txtSOHD.getText());
        n1.setNgHD(txtNGHD.getText());
        n1.setMaKH(String.valueOf(cbbMAKH.getSelectedItem()));
        n1.setMaNV(String.valueOf(cbbMANV.getSelectedItem()));
        n1.setTriGia(Long.parseLong(txtTONG.getText()));

        if (flag==0 && new HoaDonDao().Insert(n1)) {
            flag=1;
            MessageDialogHelper.showMessageDialog(parentForm, "Hóa đơn đã được thêm!", "Thông báo!");
            loadData();
            listHD.add(n1); // them vao danh sach HD
        } else {
            if(flag!=1){
            MessageDialogHelper.showErrorDialog(parentForm, "Thêm hóa đơn không thành công!", "Thông báo!");
        }}
        
        //thêm vào chi tiết hóa đơn
       // StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtSL, sb, "Số lượng không được để trống.");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        CTHD n = new CTHD();
        n.setSoHD(SOHDTV);
        n.setMaSP(selectedItem1);
        n.setSL(Integer.parseInt(txtSL.getText()));
        if (new CTHDDAO().Insert(n)) {
            MessageDialogHelper.showMessageDialog(parentForm, "CTHD đã được thêm!", "Thông báo!");
            loadData();
        } else {
            MessageDialogHelper.showErrorDialog(parentForm, "Thêm CTHD không thành công!", "Thông báo!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        StringBuilder sb = new StringBuilder();

        DataValidator.validateEmpty(txtSL, sb, "Số lượng không được để trống.");
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }

        if (MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn cập nhật chi tiết hóa đơn không?",
            "Hỏi") == JOptionPane.NO_OPTION) {
        return;
        }
        CTHD n = new CTHD();
        n.setSoHD(txtSOHD.getText());
        n.setMaSP(selectedItem1);
        n.setSL(Integer.parseInt(txtSL.getText()));
        if (new CTHDDAO().Update(n)) {
            MessageDialogHelper.showMessageDialog(parentForm, "CTHD đã được cập nhật!", "Thông báo!");
            loadData();
        } else {
            MessageDialogHelper.showMessageDialog(parentForm, "Cập nhật không thành công do lỗi!", "Thông báo!");
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        StringBuilder sb = new StringBuilder();
        if (sb.length() > 0) {
            MessageDialogHelper.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if (MessageDialogHelper.showConfirmDialog(parentForm, "Bạn có muốn xoá CTHD không?",
            "Hỏi") == JOptionPane.NO_OPTION) {
        return;
        }
        CTHDDAO dao = new CTHDDAO();
        if (dao.Delete(SOHDTV,selectedItem1)) {
            MessageDialogHelper.showMessageDialog(parentForm, "CTHD đã được xóa!", "Thông báo!");
            loadData();
            btnLamMoiActionPerformed(evt);
        } else {
            MessageDialogHelper.showMessageDialog(parentForm, "Xóa không thành công do lỗi!", "Thông báo!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed
int shd;
    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        // TODO add your handling code here:
        HoaDonDao n = new HoaDonDao();
        String hd=""; 
    try {
        hd= n.FindMaxID();
    } catch (Exception ex) {
        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
    }
    
     shd=Integer.parseInt(hd)+1;
     txtSOHD.setText(String.valueOf(shd));
    // sohd=Integer.parseInt(hd)+1;
        new HDBHPanel(shd);
       
      flag=0;
     btnLamMoiActionPerformed(evt);
          txtNGHD.setText("");
        txtHOTEN.setText("");
        txtTENNV.setText("");
        txtSODT.setText("");
        txtDCHI.setText("");
     //txtSOHD.setText(String.valueOf(Sohd_present+1));
     
     
    }//GEN-LAST:event_btnLoadActionPerformed

private void showCombo()  {
     NhanVienDao dao = new NhanVienDao();
        List<String> data = null;
        try {
            data = dao.getData();
        } catch (Exception ex) {
            Logger.getLogger(HDBHPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String string : data) {
           cbbMANV.addItem(string);
        }   
    }
private void showCombo1()  {
     KhachHangDao dao = new KhachHangDao();
        List<String> data = null;
        try {
            data = dao.getData();
        } catch (Exception ex) {
            Logger.getLogger(HDBHPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (String string : data) {
           cbbMAKH.addItem(string);
           
        }  
        cbbMAKH.addItem("NULL");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMAKH;
    private javax.swing.JComboBox<String> cbbMANV;
    private javax.swing.JComboBox<String> cbbMASP;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblCHITIET;
    private javax.swing.JTextField txtDCHI;
    private javax.swing.JTextField txtGIA;
    private javax.swing.JTextField txtHOTEN;
    private javax.swing.JTextField txtNGHD;
    private javax.swing.JTextField txtNUOCSX;
    private javax.swing.JTextField txtSL;
    private javax.swing.JTextField txtSODT;
    private javax.swing.JTextField txtSOHD;
    private javax.swing.JTextField txtTENNV;
    private javax.swing.JTextField txtTENSP;
    private javax.swing.JTextField txtTONG;
    private javax.swing.JTextField txtTONGGIA;
    // End of variables declaration//GEN-END:variables
}
